import { createClient } from '@supabase/supabase-js';
const supabase=createClient('https://jrudwnrorufmxjtjtwip.supabase.co','sb_publishable_RdYwFepv4SzTxHg2jiEVVg_nYFfQKxs');
const app=document.querySelector('#app');
let orgId=null, employee=null, role=null;
const q=s=>document.querySelector(s), v=s=>q(s)?.value?.trim()||'';
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const fmt=d=>d?new Intl.DateTimeFormat('it-IT',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(d+'T12:00:00')):'';
function deviceId(){let x=localStorage.getItem('ff_device_id');if(!x){x=crypto.randomUUID();localStorage.setItem('ff_device_id',x)}return x}
function top(name,sub=''){return `<header class="top"><div><div class="brand">FerieFlow</div><div class="topsub">${esc(sub)}</div></div><div class="topactions"><span class="pill">${esc(name)}</span><button class="btn light" id="logout">Esci</button></div></header>`}
function logoutWire(){q('#logout')?.addEventListener('click',async()=>{await supabase.auth.signOut();landing()})}
function landing(){app.innerHTML=`<div class="shell"><header class="top marketing"><div class="brand">FerieFlow</div><button class="btn light" id="focusLogin">Accedi</button></header><section class="hero landing"><div><span class="eyebrow">GESTIONE ASSENZE PER PMI</span><h1>Ferie e permessi, senza caos.</h1><p>Richieste dal telefono, approvazioni in pochi secondi, tutto ordinato in un'unica app.</p><div class="heroactions"><button class="btn primary big" id="start">Prova gratis 14 giorni</button><span class="micro">Nessuna carta richiesta</span></div></div><div class="panel authbox"><div class="stack"><h2>Crea la tua azienda</h2><input class="input" id="email" type="email" placeholder="Email aziendale"><input class="input" id="password" type="password" placeholder="Password"><input class="input" id="company" placeholder="Nome azienda"><input class="input" id="vat" placeholder="Partita IVA (consigliata)"><button class="btn primary" id="signup">Inizia la prova gratuita</button><button class="btn ghost" id="login">Ho già un account</button><div id="msg" class="muted"></div></div></div></section><section class="featuregrid"><div class="feature"><div class="icon">✓</div><h3>Richieste semplici</h3><p>Ferie e permessi direttamente dal telefono.</p></div><div class="feature"><div class="icon">⚡</div><h3>Approvazioni veloci</h3><p>Il responsabile decide senza chat o fogli Excel.</p></div><div class="feature"><div class="icon">🔗</div><h3>Inviti automatici</h3><p>Ogni collaboratore riceve il proprio accesso personale.</p></div></section><section class="pricing"><span class="eyebrow">PREZZI DOPO LA PROVA</span><h2>14 giorni gratis, poi scegli tu.</h2><div class="pricegrid"><div class="pricecard"><b>Starter</b><strong>29 €<small>/mese</small></strong><span>fino a 10 collaboratori</span></div><div class="pricecard featured"><b>Business</b><strong>49 €<small>/mese</small></strong><span>fino a 30 collaboratori</span></div><div class="pricecard"><b>Pro</b><strong>79 €<small>/mese</small></strong><span>fino a 100 collaboratori</span></div></div></section></div>`;
q('#start').onclick=q('#focusLogin').onclick=()=>q('#email').focus();q('#signup').onclick=signup;q('#login').onclick=login}
async function signup(){const email=v('#email'),password=v('#password'),company=v('#company'),vat=v('#vat');if(!email||!password||!company)return msg('Compila email, password e nome azienda.');msg('Creo l’account...');const {data,error}=await supabase.auth.signUp({email,password});if(error)return msg(error.message);localStorage.setItem('ff_pending',JSON.stringify({company,vat}));if(!data.session)return msg('Conferma l’email ricevuta, poi torna qui e accedi.');await bootstrap(company,vat)}
async function login(){const {error}=await supabase.auth.signInWithPassword({email:v('#email'),password:v('#password')});if(error)return msg(error.message);await load()}
function msg(t){const x=q('#msg');if(x)x.textContent=t}
async function bootstrap(company,vat){const {data,error}=await supabase.functions.invoke('saas-bootstrap',{body:{name:company}});if(error)return msg(error.message);orgId=data.organization?.id||data.organization_id;const {error:trialErr}=await supabase.functions.invoke('saas-start-trial',{body:{organization_id:orgId,vat_number:vat||'',device_id:deviceId()}});if(trialErr)return msg(trialErr.message);localStorage.removeItem('ff_pending');await load()}
async function load(){const {data:{user}}=await supabase.auth.getUser();if(!user)return landing();const {data:m}=await supabase.from('saas_memberships').select('organization_id,role').eq('user_id',user.id).maybeSingle();if(m){orgId=m.organization_id;role=m.role;const {data:org}=await supabase.from('saas_organizations').select('*').eq('id',orgId).single();if(org?.trial_status==='not_started'){let pending={};try{pending=JSON.parse(localStorage.getItem('ff_pending')||'{}')}catch{};return bootstrap(pending.company||org.name,pending.vat||org.vat_number||'')}return admin()};const {data:e}=await supabase.from('saas_employees').select('*').eq('auth_user_id',user.id).maybeSingle();if(e){employee=e;orgId=e.organization_id;return employeeView()}landing()}
async function admin(){const [{data:org},{data:emps},{data:reqs}]=await Promise.all([supabase.from('saas_organizations').select('*').eq('id',orgId).single(),supabase.from('saas_employees').select('*').eq('organization_id',orgId).order('created_at'),supabase.from('saas_absence_requests').select('*,saas_employees(first_name,last_name)').eq('organization_id',orgId).order('created_at',{ascending:false})]);const pending=(reqs||[]).filter(r=>r.status==='pending');app.innerHTML=`<div class="shell dashboard">${top(org.name,role==='owner'?'Proprietario':'Amministratore')}<main class="dashwrap"><section class="dashhead"><div><span class="eyebrow">PANORAMICA</span><h1>Ciao 👋</h1><p>La tua azienda è attiva in prova gratuita.</p></div><button class="btn primary big" id="invite">+ Invita collaboratore</button></section><section class="stats"><div class="stat"><span>DA APPROVARE</span><strong>${pending.length}</strong><small>richieste in attesa</small></div><div class="stat"><span>COLLABORATORI</span><strong>${(emps||[]).length}</strong><small>persone inserite</small></div><div class="stat"><span>PROVA</span><strong>${org.trial_status==='active'?'Attiva':'—'}</strong><small>${org.trial_ends_at?'fino al '+fmt(org.trial_ends_at.slice(0,10)):''}</small></div><div class="stat accent"><span>CARTA</span><strong>No</strong><small>non richiesta durante la prova</small></div></section><section class="twocol"><div class="card"><h3>Richieste</h3>${(reqs||[]).slice(0,10).map(r=>`<div class="request"><div class="grow"><strong>${esc(r.saas_employees?.first_name||'')} ${esc(r.saas_employees?.last_name||'')}</strong><div class="muted">${esc(r.request_type)} · ${fmt(r.start_date)}${r.end_date!==r.start_date?' → '+fmt(r.end_date):''}</div></div><span class="badge ${r.status}">${r.status==='pending'?'In attesa':r.status==='approved'?'Approvata':'Rifiutata'}</span>${r.status==='pending'?`<div class="actions"><button class="iconbtn yes" data-a="${r.id}">✓</button><button class="iconbtn no" data-r="${r.id}">×</button></div>`:''}</div>`).join('')||'<div class="empty">Nessuna richiesta.</div>'}</div><div class="card"><h3>Collaboratori</h3>${(emps||[]).map(e=>`<div class="employee"><div class="avatar">${esc((e.first_name||'?')[0])}${esc((e.last_name||'?')[0])}</div><div class="grow"><strong>${esc(e.first_name)} ${esc(e.last_name)}</strong><div class="muted">${esc(e.email||'')}</div></div><span class="badge approved">${e.auth_user_id?'Attivo':'Invitato'}</span></div>`).join('')||'<div class="empty">Nessun collaboratore.</div>'}</div></section></main><div id="modal"></div></div>`;logoutWire();q('#invite').onclick=inviteModal;document.querySelectorAll('[data-a]').forEach(b=>b.onclick=()=>decide(b.dataset.a,'approved'));document.querySelectorAll('[data-r]').forEach(b=>b.onclick=()=>decide(b.dataset.r,'rejected'))}
async function decide(id,status){const note=status==='rejected'?(prompt('Motivo del rifiuto (facoltativo):')||null):null;const {error}=await supabase.from('saas_absence_requests').update({status,admin_note:note,decided_at:new Date().toISOString()}).eq('id',id);if(error)return alert(error.message);admin()}
function inviteModal(){q('#modal').innerHTML=`<div class="overlay"><div class="modal"><div class="modalhead"><h2>Invita collaboratore</h2><button class="x" id="close">×</button></div><div class="stack"><div class="two"><input class="input" id="fn" placeholder="Nome"><input class="input" id="ln" placeholder="Cognome"></div><input class="input" id="em" type="email" placeholder="Email"><button class="btn primary" id="send">Crea invito</button><div class="muted" id="imsg"></div></div></div></div>`;q('#close').onclick=()=>q('#modal').innerHTML='';q('#send').onclick=sendInvite}
async function sendInvite(){const first_name=v('#fn'),last_name=v('#ln'),email=v('#em');if(!first_name||!last_name||!email)return q('#imsg').textContent='Compila tutti i campi.';q('#imsg').textContent='Creo l’invito...';const {data,error}=await supabase.functions.invoke('saas-invite-employee',{body:{organization_id:orgId,first_name,last_name,email,redirect_to:location.origin+'/saas.html'}});if(error)return q('#imsg').textContent=error.message;q('#imsg').innerHTML=`Invito pronto. <button class="btn ghost" id="copy">Copia link</button>`;q('#copy').onclick=async()=>{await navigator.clipboard.writeText(data.invite_url||'');q('#imsg').textContent='Link copiato.'}}
async function employeeView(){const [{data:org},{data:reqs},{data:settings}]=await Promise.all([supabase.from('saas_organizations').select('*').eq('id',orgId).single(),supabase.from('saas_absence_requests').select('*').eq('employee_id',employee.id).order('created_at',{ascending:false}),supabase.from('saas_settings').select('*').eq('organization_id',orgId).maybeSingle()]);app.innerHTML=`<div class="shell employeeapp">${top(org.name,'Area collaboratore')}<main class="mobilewrap"><section class="welcome"><span class="eyebrow">AREA PERSONALE</span><h1>Ciao ${esc(employee.first_name)} 👋</h1><p>Invia una richiesta e controllane lo stato.</p></section><button class="btn primary requestbtn" id="new">+ Nuova richiesta</button><section class="card"><h3>Le mie richieste</h3>${(reqs||[]).map(r=>`<div class="request"><div class="grow"><strong>${esc(r.request_type)}</strong><div class="muted">${fmt(r.start_date)}${r.end_date!==r.start_date?' → '+fmt(r.end_date):''}</div></div><span class="badge ${r.status}">${r.status==='pending'?'In attesa':r.status==='approved'?'Approvata':'Rifiutata'}</span></div>`).join('')||'<div class="empty">Nessuna richiesta.</div>'}</section><div class="policy">Preavviso minimo: ${settings?.min_notice_days??5} giorni.</div></main><div id="modal"></div></div>`;logoutWire();q('#new').onclick=()=>requestModal(settings||{})}
function requestModal(settings){q('#modal').innerHTML=`<div class="overlay"><div class="modal"><div class="modalhead"><h2>Nuova richiesta</h2><button class="x" id="close">×</button></div><div class="stack"><select class="input" id="type"><option value="ferie">Ferie</option><option value="permesso">Permesso</option></select><div class="two"><input class="input" type="date" id="from"><input class="input" type="date" id="to"></div><textarea class="input" id="reason" placeholder="Nota (facoltativa)"></textarea><button class="btn primary" id="submit">Invia richiesta</button><div id="rmsg" class="muted"></div></div></div></div>`;q('#close').onclick=()=>q('#modal').innerHTML='';q('#submit').onclick=()=>submitRequest(settings)}
async function submitRequest(settings){const from=v('#from'),to=v('#to')||from,type=v('#type');if(!from)return q('#rmsg').textContent='Seleziona la data.';const days=Math.floor((new Date(from+'T12:00:00')-new Date(new Date().toDateString()))/86400000);if(days<(settings.min_notice_days??5))return q('#rmsg').textContent=`Serve un preavviso di ${settings.min_notice_days??5} giorni.`;const {error}=await supabase.from('saas_absence_requests').insert({organization_id:orgId,employee_id:employee.id,request_type:type,start_date:from,end_date:to,reason:v('#reason')||null,status:'pending'});if(error)return q('#rmsg').textContent=error.message;q('#modal').innerHTML='';employeeView()}
load();