import { createClient } from '@supabase/supabase-js';
const SUPABASE_URL='https://jrudwnrorufmxjtjtwip.supabase.co';
const SUPABASE_KEY='sb_publishable_RdYwFepv4SzTxHg2jiEVVg_nYFfQKxs';
const supabase=createClient(SUPABASE_URL,SUPABASE_KEY);
const app=document.querySelector('#app');
let orgId=null;

function renderLanding(){app.innerHTML=`<div class="shell"><div class="top"><div class="brand">FerieFlow</div></div><section class="hero"><div><h1>Ferie e permessi, senza caos.</h1><p>Il collaboratore invia la richiesta dal telefono. Tu approvi in pochi secondi. Niente fogli, niente messaggi persi.</p><button class="btn primary" id="start">Inizia prova gratuita</button></div><div class="panel"><div class="stack"><input class="input" id="email" placeholder="Email aziendale"><input class="input" id="password" type="password" placeholder="Password"><input class="input" id="company" placeholder="Nome azienda"><button class="btn primary" id="signup">Crea account</button><button class="btn ghost" id="login">Accedi</button><div class="muted" id="msg"></div></div></div></section><section class="grid"><div class="card"><div class="kpi">10 sec</div><div class="muted">per approvare una richiesta</div></div><div class="card"><div class="kpi">100%</div><div class="muted">mobile e installabile</div></div><div class="card"><div class="kpi">1 link</div><div class="muted">automatico per ogni collaboratore</div></div></section></div>`;
qs('#start').onclick=()=>qs('#email').focus();
qs('#signup').onclick=signup;
qs('#login').onclick=login;
}

async function signup(){const email=val('#email'),password=val('#password'),company=val('#company');msg('Creo il tuo account...');const {data,error}=await supabase.auth.signUp({email,password});if(error)return msg(error.message);if(!data.session)return msg('Controlla la tua email e conferma l’account.');await bootstrap(company);}
async function login(){const {error}=await supabase.auth.signInWithPassword({email:val('#email'),password:val('#password')});if(error)return msg(error.message);await loadDashboard();}
async function bootstrap(name){const {data,error}=await supabase.functions.invoke('saas-bootstrap',{body:{name}});if(error)return msg(error.message);orgId=data.organization?.id||data.organization_id;await loadDashboard();}

async function loadDashboard(){const {data:{user}}=await supabase.auth.getUser();if(!user)return renderLanding();const {data:membership}=await supabase.from('saas_memberships').select('organization_id,role').eq('user_id',user.id).maybeSingle();if(!membership)return renderOnboarding();orgId=membership.organization_id;const {data:org}=await supabase.from('saas_organizations').select('*').eq('id',orgId).single();const {data:employees}=await supabase.from('saas_employees').select('*').eq('organization_id',orgId).order('created_at');const {data:reqs}=await supabase.from('saas_absence_requests').select('*').eq('organization_id',orgId).order('created_at',{ascending:false}).limit(8);renderDashboard(org,employees||[],reqs||[]);}
function renderOnboarding(){app.innerHTML=`<section class="hero"><div><h1>Configura la tua azienda</h1><p>Ci vogliono meno di due minuti.</p></div><div class="panel stack"><input class="input" id="company2" placeholder="Nome azienda"><button class="btn primary" id="createOrg">Continua</button><div id="msg" class="muted"></div></div></section>`;qs('#createOrg').onclick=()=>bootstrap(val('#company2'));}
function renderDashboard(org,employees,reqs){app.innerHTML=`<div class="top"><div class="brand">${esc(org.name)}</div></div><section class="hero"><div><h1>Gestione assenze semplice.</h1><p>${employees.length} collaboratori · Piano ${esc(org.plan)}</p><button class="btn primary" id="invite">+ Invita collaboratore</button></div><div class="panel"><div class="kpi">${reqs.filter(r=>r.status==='pending').length}</div><div class="muted">richieste da approvare</div></div></section><section class="grid"><div class="card"><h3>Collaboratori</h3><div id="employees">${employees.map(e=>`<div class="employee"><div><strong>${esc(e.first_name)} ${esc(e.last_name)}</strong><div class="muted">${esc(e.email||'')}</div></div><span class="badge">Attivo</span></div>`).join('')||'<div class="muted">Nessun collaboratore</div>'}</div></div><div class="card"><h3>Richieste recenti</h3>${reqs.map(r=>`<div class="employee"><div><strong>${esc(r.request_type)}</strong><div class="muted">${r.start_date}${r.end_date!==r.start_date?' → '+r.end_date:''}</div></div><span class="badge">${esc(r.status)}</span></div>`).join('')||'<div class="muted">Nessuna richiesta</div>'}</div><div class="card"><h3>Il tuo piano</h3><div class="kpi">14 giorni</div><div class="muted">prova gratuita con carta richiesta al checkout</div></div></section><div id="modal"></div>`;qs('#invite').onclick=showInvite;}
function showInvite(){qs('#modal').innerHTML=`<div class="panel" style="position:fixed;inset:auto 18px 18px 18px;max-width:520px;margin:auto;z-index:20"><h3>Invita collaboratore</h3><div class="stack"><input class="input" id="fn" placeholder="Nome"><input class="input" id="ln" placeholder="Cognome"><input class="input" id="em" placeholder="Email"><button class="btn primary" id="sendInvite">Genera invito</button><button class="btn ghost" id="close">Chiudi</button><div id="inviteMsg" class="muted"></div></div></div>`;qs('#close').onclick=()=>qs('#modal').innerHTML='';qs('#sendInvite').onclick=inviteEmployee;}
async function inviteEmployee(){qs('#inviteMsg').textContent='Genero il link...';const {data,error}=await supabase.functions.invoke('saas-invite-employee',{body:{organization_id:orgId,first_name:val('#fn'),last_name:val('#ln'),email:val('#em'),redirect_to:location.origin+'/saas.html'}});if(error){qs('#inviteMsg').textContent=error.message;return;}qs('#inviteMsg').innerHTML=`Invito creato. <button class="btn ghost" id="copy">Copia link</button>`;qs('#copy').onclick=async()=>{await navigator.clipboard.writeText(data.invite_url);qs('#inviteMsg').textContent='Link copiato. Ora puoi inviarlo via WhatsApp o email.';};}
function qs(s){return document.querySelector(s)}function val(s){return qs(s)?.value?.trim()||''}function msg(t){const e=qs('#msg');if(e)e.textContent=t}function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
supabase.auth.onAuthStateChange(()=>{});loadDashboard();
