-- Accesso tablet officina tramite link riservato, senza email e password
-- Eseguire nel SQL Editor di Supabase.

create table if not exists public.officina_access_links (
  id bigint generated by default as identity primary key,
  access_token uuid not null unique default gen_random_uuid(),
  active boolean not null default true,
  label text not null default 'Tablet officina',
  created_at timestamptz not null default now()
);

alter table public.officina_access_links enable row level security;
revoke all on public.officina_access_links from anon, authenticated;

drop policy if exists "officina reads clients" on public.clients;
drop policy if exists "officina reads jobs" on public.jobs;
drop policy if exists "officina reads painting deliveries" on public.painting_deliveries;
drop function if exists public.is_simpro_officina();

create or replace function public.get_officina_board(p_token uuid)
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select case
    when not exists (
      select 1 from public.officina_access_links l
      where l.access_token = p_token and l.active = true
    ) then jsonb_build_object('ok', false)
    else jsonb_build_object(
      'ok', true,
      'clients', coalesce((
        select jsonb_agg(jsonb_build_object('id', c.id, 'name', c.name))
        from public.clients c
        where exists (
          select 1 from public.jobs j
          where j.client_id = c.id and j.completed_at is null and j.has_painting = true
        )
      ), '[]'::jsonb),
      'jobs', coalesce((
        select jsonb_agg(jsonb_build_object(
          'id', j.id,
          'client_id', j.client_id,
          'title', j.title,
          'code', j.code,
          'current_step', j.current_step,
          'painter', j.painter,
          'has_painting', j.has_painting,
          'note', j.note,
          'admin_notes', j.admin_notes,
          'due_date', j.due_date,
          'updated_at', j.updated_at
        ) order by j.updated_at desc)
        from public.jobs j
        where j.completed_at is null and j.has_painting = true
      ), '[]'::jsonb),
      'deliveries', coalesce((
        select jsonb_agg(to_jsonb(d) order by d.created_at desc)
        from public.painting_deliveries d
      ), '[]'::jsonb)
    )
  end;
$$;

revoke all on function public.get_officina_board(uuid) from public;
grant execute on function public.get_officina_board(uuid) to anon, authenticated;

insert into public.officina_access_links (label)
select 'Tablet officina'
where not exists (select 1 from public.officina_access_links);

select access_token, active, label, created_at
from public.officina_access_links
order by created_at desc;
