-- Aggiornamento gestionale SIMPRO del 27/07/2026
alter table public.jobs add column if not exists workflow_type text not null default 'completa' check (workflow_type in ('completa','lamiere'));
alter table public.jobs add column if not exists current_step text not null default 'materiale_ordinato';
alter table public.jobs add column if not exists has_galvanizing boolean not null default false;
alter table public.jobs add column if not exists has_painting boolean not null default false;
alter table public.jobs add column if not exists priority text not null default 'normale' check (priority in ('urgente','alta','normale','bassa'));
alter table public.jobs add column if not exists painter text check (painter is null or painter in ('DAMAS','SOSAM','METALLIKA','GALLO'));
alter table public.jobs add column if not exists admin_notes text;
alter table public.jobs add column if not exists due_date date;
alter table public.jobs add column if not exists payment_notice text;

create table if not exists public.audit_log (
  id bigint generated by default as identity primary key,
  entity_type text not null,
  entity_id text,
  action text not null,
  description text,
  user_email text default (auth.jwt() ->> 'email'),
  created_at timestamptz not null default now()
);

alter table public.audit_log enable row level security;
drop policy if exists "simpro admins manage audit log" on public.audit_log;
create policy "simpro admins manage audit log" on public.audit_log for all to authenticated
using (public.is_simpro_admin()) with check (public.is_simpro_admin());
grant select, insert on public.audit_log to authenticated;

create or replace function public.get_client_portal(p_token uuid)
returns jsonb language sql stable security definer set search_path = public as $$
  select jsonb_build_object(
    'client', jsonb_build_object('name', c.name, 'contact_name', c.contact_name),
    'jobs', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', j.id,
        'title', j.title,
        'code', j.code,
        'phase', j.phase,
        'progress', j.progress,
        'delivery', j.delivery,
        'due_date', j.due_date,
        'note', j.note,
        'requires_installation', j.requires_installation,
        'payment_notice', j.payment_notice,
        'workflow_type', j.workflow_type,
        'current_step', j.current_step,
        'has_galvanizing', j.has_galvanizing,
        'has_painting', j.has_painting,
        'updated_at', j.updated_at
      ) order by j.created_at desc)
      from public.jobs j where j.client_id = c.id
    ), '[]'::jsonb)
  )
  from public.clients c
  where c.access_token = p_token and c.active = true;
$$;

revoke all on function public.get_client_portal(uuid) from public;
grant execute on function public.get_client_portal(uuid) to anon, authenticated;


-- Consegne autista verso verniciatori
create table if not exists public.painting_deliveries (
  id bigint generated by default as identity primary key,
  job_code text,
  client_name text not null,
  painter text not null check (painter in ('DAMAS','SOSAM','METALLIKA','GALLO')),
  driver_name text,
  notes text,
  checked boolean not null default false,
  checked_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.painting_deliveries enable row level security;

drop policy if exists "drivers create painting deliveries" on public.painting_deliveries;
create policy "drivers create painting deliveries" on public.painting_deliveries
for insert to anon, authenticated
with check (true);

drop policy if exists "simpro admins read painting deliveries" on public.painting_deliveries;
create policy "simpro admins read painting deliveries" on public.painting_deliveries
for select to authenticated
using (public.is_simpro_admin());

drop policy if exists "simpro admins update painting deliveries" on public.painting_deliveries;
create policy "simpro admins update painting deliveries" on public.painting_deliveries
for update to authenticated
using (public.is_simpro_admin())
with check (public.is_simpro_admin());

grant insert on public.painting_deliveries to anon, authenticated;
grant select, update on public.painting_deliveries to authenticated;
